// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzcipwazeeizgwrzyqdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6Y2lwd2F6ZWVpemd3cnp5cWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTM2NDgsImV4cCI6MjA2NjI4OTY0OH0.zLaoy_VHPPs3SQCaR-rHwKmySxBAOWus0se7GIuYP4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);