name: Deploy to cPanel

on:
  push:
    branches:
      - live
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Clear npm cache
        run: npm cache clean --force
        
      - name: Install dependencies
        run: npm ci --only=production
        env:
          NODE_ENV: production
        
      - name: Build React App
        run: npm run build --if-present
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy to cPanel
        run: rsync -rlgoDzvc --delete build/ mafadmpc@${{ secrets.CPANEL_HOST }}:~/academy/staging/
